In [4]:
import numpy as np

In [11]:
a = np.array([i for i in range(10)]).reshape(2,5)

In [12]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
a == b

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [21]:
b = np.array([[0,1,2,3,4], [5,6,7,8,9]])

In [23]:
np.sum(a == b) == row*col

True

In [29]:
a = np.argwhere(b==6)

In [30]:
a

array([[1, 1]])

In [33]:
row,col = a[0]

In [34]:
row

1

In [35]:
moving_directions = [(1,0), (-1, 0), (0, 1), [0, -1]]

In [36]:
for a,b in moving_directions:
    print (a,b)

1 0
-1 0
0 1
0 -1


In [37]:
temp = set()

In [38]:
temp.add(b)

In [39]:
b in temp

True

In [42]:
import numpy as np
import copy
def movesToSolve(puzzle):
    # Write your code here
    # It's like finding the shortest path in a graph, and each node represents a situation, if one situation can reach to another situation in one step, then we can use an edge to connect those two situations.
    # Using BFS: 1. terminate condition
               # 2. a set to track visited node, avoiding cycle
    

    row = len(puzzle)
    col = len(puzzle[0])
    terminate = [i for i in range(row*col)]
    # terminate conditions
    terminate_matrix = np.array(terminate).reshape(row, col)
    visited = []
    step = 0
    moving_directions = [(1,0), (-1, 0), (0, 1), [0, -1]]
    
    exist_situation = [np.array(puzzle)]
    while exist_situation:
        next_situation = []
        for each_situation in exist_situation:
            print (each_situation)
            # check if equal to terminate condition
            if np.sum(each_situation == terminate_matrix) == row*col:
                return step
            if each_situation not in visited:
                visited.append(each_situation)

                # find index of 0
                idx = np.argwhere(each_situation==0)
                row_0, col_0 = idx[0]
                # exchange positions for four directions
                for h, v in moving_directions:
                    x_temp = row_0 + h
                    y_temp = col_0 + v
                # check boundary
                    if 0<=x_temp<row and 0 <=y_temp<col:
                        copy_situation = copy.deepcopy(each_situation)
                        copy_situation[row_0][col_0], copy_situation[x_temp][y_temp] = copy_situation[x_temp][y_temp], copy_situation[row_0][col_0]
                    next_situation.append(copy_situation)
        step+=1
        exist_situation = next_situation
    
    return -1

In [43]:
movesToSolve([[1, 0, 2],[3, 4, 5],[6, 7, 8]])

[[1 0 2]
 [3 4 5]
 [6 7 8]]
[[1 4 2]
 [3 0 5]
 [6 7 8]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [48]:
import numpy as np
import copy
def movesToSolve(puzzle):
    # Write your code here
    # It's like finding the shortest path in a graph, and each node represents a situation, if one situation can reach to another situation in one step, then we can use an edge to connect those two situations.
    # Using BFS: 1. terminate condition
               # 2. a set to track visited node, avoiding cycle
    

    row = len(puzzle)
    col = len(puzzle[0])
    terminate = [i for i in range(row*col)]
    # terminate conditions
    puzzle_ = [i for i in range(row*col)]
    for i in range(row):
        for j in range(col):
            puzzle_[i*col+j] = puzzle[i][j]
            
    
    visited = set()
    step = 0
    moving_directions = [(1,0), (-1, 0), (0, 1), [0, -1]]
    
    exist_situation = [puzzle_]
    while exist_situation:
        next_situation = []
        for each_situation in exist_situation:
            # check if equal to terminate condition
            if each_situation == terminate:
                return step
            if tuple(each_situation) not in visited:
                visited.add(tuple(each_situation))

                # find index of 0
                idx = each_situation.index(0)
                print (idx)
                row_0, col_0 = divmod(idx, col)
                # exchange positions for four directions
                for h, v in moving_directions:
                    x_temp = row_0 + h
                    y_temp = col_0 + v
                # check boundary
                    if 0<=x_temp<row and 0 <=y_temp<col:
                        copy_situation = copy.deepcopy(each_situation)
                        copy_situation[x_temp*col+y_temp], copy_situation[idx] = copy_situation[idx], copy_situation[x_temp*col+y_temp]
                    next_situation.append(copy_situation)
        step+=1
        exist_situation = next_situation
    
    return -1

In [49]:
movesToSolve([[1, 0, 2],[3, 4, 5],[6, 7, 8]])

1
4
2


1